version: "3.3"

services:
  db:
    container_name: stonepay_db
    image: postgres
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=stonepay_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  phoenix:
    build: .
    links:
      - "db:dockerdb"
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - db
